### ISSUE TITLE
Mobile users crashing when wire is used

### ISSUE THREAD

**Issue by Ghoose1** [Moneylover3246/Crossplay#11]
Hi, so i have been using this plugin for testing recently and noticed quite a large bug, in that when a wire machine as simple as a torch is activated mobile players generally receive their games crashing. one of my friends using mobile will crash immediately upon the lever being used, but another takes a few tries to crash. I know this probably isn't solvable from the plugin but i thought i would report it anyway.

**Comment by Moneylover3246** [comment]
What version of the plugin are you using?

**Comment by Ghoose1** [comment]
Sorry for the late reply, I am using the most recent version of tshock version (4.5.5), as well as the most recent version of the plugin. It is most likely being caused by the other plugins being used (journey mode mixer and dimensions), but still thought it was worth reporting due to only the mobile players being affected.

**Comment by Moneylover3246** [comment]
> using crossplay with dimensions might cause some minor issues with things like random crashes. If you know how to code (in typescript), your best bet is to create a crossplay extension for dimensions. If not, try politely asking the owner to make one.
