### ISSUE TITLE
Pets Problem

### ISSUE THREAD

**Issue by hdseventh** [Moneylover3246/Crossplay#12]
I found a bug where players using Terraria 1.4.2.3 will stuck at "Receiving tiles data..." loading screen if someone equipped the new 1.4.3(tested with Bone Eye) Pets in the server. But players using 1.4.0.5 can still join the server.

**Comment by Moneylover3246** [comment]
Thanks for the report! This issue was fixed in the 1.5.1 hotfix 
https://github.com/Moneylover3246/Crossplay/releases/tag/1.5.1
