### ISSUE TITLE
here is a bug

### ISSUE THREAD

**Issue by mxtilx** [Moneylover3246/Crossplay#14]
![Screenshot_2022-02-02-17-19-33-54](https://user-images.githubusercontent.com/96869052/152126546-5205a159-847c-4813-a8a1-a8ccc04d89c5.jpg)
![Screenshot_2022-02-02-17-19-20-72](https://user-images.githubusercontent.com/96869052/152126560-81f20b28-00be-4a56-9cbd-5e0182bc4ac1.jpg)

**Comment by Moneylover3246** [comment]
You're using an earlier version of TShock. Update TShock to the latest version (4.5.12) so the plugin works properly
