### ISSUE TITLE
TShock update

### ISSUE THREAD

**Issue by GILLESMaster** [Moneylover3246/Crossplay#15]
Mobile user joining via Crossplay is 'connecting' from version 1.4.3.2

while the server is on 1.4.3.4, and thus disconnects the user.

**Comment by 1419427247** [comment]
> Mobile user joining via Crossplay is 'connecting' from version 1.4.3.2
> 
> while the server is on 1.4.3.4, and thus disconnects the user.

你可以更新配置一下依赖项，重新编译一下就行了

**Comment by MaksDragon** [comment]
+. Need to update plugin. mobile players cant connect to new version 1.4.3.4

**Comment by Kojirremer** [comment]
Moneylover said on Discord that he's on vacation right now. We will all have to wait for a few days (unless an updated fork pops up elsewhere).

**Comment by gohjoseph** [comment]
You can take a look at my fork, I've made a PR in the meantime.

**Comment by MaksDragon** [comment]
> You can take a look at my fork, I've made a PR in the meantime.

your plugin doesnt work properly. When mobile players connect to server they have game quit. You can test it on my server. Server have your plugin right now. Try to connect from mobile version IP - 80.85.137.146
Port - 7777

**Comment by Moneylover3246** [comment]
Everything has been updated, and the plugin should work properly on the latest TShock release.
