### ISSUE TITLE
Will not work on latest mobile version of terraria.

### ISSUE THREAD

**Issue by BalancedCello85** [Moneylover3246/Crossplay#20]
I'm hosting a server with this plugin and it does not work with the latest mobile version, v1.4.0.5.2 I believe its on.  Any suggestions?

**Comment by Moneylover3246** [comment]
Could you tell me what version of TShock you're using, along with the version of this plugin?

**Comment by Moneylover3246** [comment]
Make sure TShock is on 4.5.15a, not 4.5.15.

**Comment by BalancedCello85** [comment]
It is updated to that version.
![Screenshot_20220304-140103_Samsung Internet](https://user-images.githubusercontent.com/100818963/156825536-45e25e1a-5a54-4383-9c5d-4b31cc1169bd.jpg)

**Comment by Moneylover3246** [comment]
Make sure `TShockAPI.dll` is updated to 4.5.15, and that `OTAPI.dll` and `TerrariaServer.exe` are updated to 1.4.3.6. 

Your issue is that OTAPI and TerrariaServer.exe arent updated
