### ISSUE TITLE
TShock update

### ISSUE THREAD

**Issue by nuckle** [Moneylover3246/Crossplay#21]
[Recent TShock update](https://github.com/Pryaxis/TShock/releases/tag/v4.5.16) break the plugin again.
People from mobile devices can't join on 1.4.3.6 version. They get an error "Lost connection. You are not using the same version as this server".

**Comment by Moneylover3246** [comment]
Make sure all of your server files are updated (most importantly `OTAPI.dll`) to 1.4.3.6. Make sure crossplay is also updated to 1.10.2

**Comment by nuckle** [comment]
Thank you! My problem was that the plugin was outdated.
