### ISSUE TITLE
Connection timeout

### ISSUE THREAD

**Issue by Bac0nio** [Moneylover3246/Crossplay#23]
I turn on the server with this plugin, when I c
![изображение_viber_2022-03-26_14-19-32-348](https://user-images.githubusercontent.com/102408948/160239203-3bb91fe9-325a-4ac6-99de-7add9fefd60d.jpg)
onnect to the server from a mobile device I get this error.

**Comment by Moneylover3246** [comment]
Assuming you're hosting locally, there's a high chance you haven't port forwarded. Other than that you may be using the wrong IP

**Comment by Bac0nio** [comment]
Is it possible to open ports if I have mobile Internet?
