### ISSUE TITLE
expert dificulty does not load in mobile

### ISSUE THREAD

**Issue by animation-is-always-taken** [Moneylover3246/Crossplay#25]
so, i was about to play a world with a firend of mine, using the right ip in a world in expert, in mine firend's phone the server refuced to let him in, but if i changed to a world in any other dificulty it does work as if nothing was wrong
![image](https://user-images.githubusercontent.com/98624703/162344194-278ecc30-2478-4fe6-8d90-c256cb534de7.png)

edit: i wrote extreme instead of hardcore

**Comment by Moneylover3246** [comment]
If "extreme" means hardcore, make sure that your friend's character also is on that difficulty. Make sure to send any kick/error messages that appear in the console

**Comment by animation-is-always-taken** [comment]
my bad, i meant expert

**Comment by NOTAD** [comment]
I have same errror
