### ISSUE TITLE
"You are not using the same version as this server"

### ISSUE THREAD

**Issue by ParronT** [Moneylover3246/Crossplay#28]
So, it's ironic but what happened is that i updated my tshock to lates and setted the game files in server plugins and the console displayed that the plugin was enabled, issue is that i tried to join the server through mobile and this happened:
![Screenshot_20220620-135351_Terraria](https://user-images.githubusercontent.com/107885460/174664281-650618be-8b68-4a77-8ce4-8c7b8d7e337b.jpg)
Normally, i'd think it's because the terraria is not updated, but my terraria mobile is in 1.4.3.2, the latest for mobiles, and i have no idea of what could be going wrong
Edit: i am using TShock 4.5.17

**Comment by ParronT** [comment]
Yeah, about that...
![Screenshot_20220622-145607_Chrome](https://user-images.githubusercontent.com/107885460/175125023-44d80c20-54b2-4568-9b2c-3084b36f3f55.jpg)

**Comment by Moneylover3246** [comment]
My recommendation would be to create a fresh copy of the server (make sure to save the config) and install any plugins you may've had before. I'd advise to also remove the `.zip` and `.gz` files, as they don't need to be in that folder

**Comment by ParronT** [comment]
So where do they belong?

**Comment by Moneylover3246** [comment]
They don't need to be in the server files. It's alright to delete them after installing the dll
