### ISSUE TITLE
update crossplataform plugin to play new version of terraria 1.4.4.0 labor of love !!!

### ISSUE THREAD

**Issue by T4SpaX** [Moneylover3246/Crossplay#32]
terraria receive a updated we need to update crossplataform plugin ...

**Comment by Rozen4334** [comment]
https://github.com/Moneylover3246/Crossplay/pull/33

**Comment by T4SpaX** [comment]
> #33

aaa understand not have players on mobile because version in mobile its 1.4.4 and in pc is 1.4.4.2,this is correct ?..
and.. Rozen how i help in this project ?

**Comment by HexedHero** [comment]
Updated here: https://github.com/Moneylover3246/Crossplay/releases/tag/2.0-beta

**Comment by adrielpax** [comment]
amazing job

Em qua., 30 de nov. de 2022 às 19:28, Moneylover3246 <
***@***.***> escreveu:
