### ISSUE TITLE
Update for 1.4.4 please

### ISSUE THREAD

**Issue by Cramram** [Moneylover3246/Crossplay#34]
It would be very appreciated

**Comment by KotMilkMeoWtwo** [comment]
+

**Comment by max2007-69** [comment]
Are you sure that this plugin will be updated for version 1.4.4.x? The developer has done ABSOLUTELY nothing on the github for 7 months, do you have any other thoughts in your head or what? Well, of course, I also hope that the plugin will be updated, but 7 months... This is somehow too much.

**Comment by max2007-69** [comment]
In general, it is better to ask other developers associated with Tshok about it, if it is possible in principle.

**Comment by HexedHero** [comment]
Updated here: https://github.com/Moneylover3246/Crossplay/releases/tag/2.0-beta
