### ISSUE TITLE
Android/mobile issue

### ISSUE THREAD

**Issue by Op0m** [Moneylover3246/Crossplay#41]
Okay so i find some glitch if you connect to Server its say "You are not using the same version as this server." And anyways i use 1.4.4.5.okay so what i want to say its Can you fix it?

**Comment by Op0m** [comment]
Oh anyways i use latest version of plugin

**Comment by MaksDragon** [comment]
wait update

**Comment by Op0m** [comment]
Yeah you're right its still pre release
