### ISSUE TITLE
1.4.4.8 Update

### ISSUE THREAD

**Issue by Toopyaaaa** [Moneylover3246/Crossplay#43]
game has been updated to 1.4.4.8 It only allows up to 1.4.4.7 pls help

**Comment by MaksDragon** [comment]
need wait to update

**Comment by SirMonkeyBoy** [comment]
#44

**Comment by poguinha** [comment]
> #44

This is already working ?

**Comment by SirMonkeyBoy** [comment]
Yeah theirs a crossplay.dll in my releases but update to this plugin when it updates
