### ISSUE TITLE
It doesn't work

### ISSUE THREAD

**Issue by GokuModoSupreme** [Moneylover3246/Crossplay#47]
I put it on the server, and in the console section it told me that it was working, but nobody can join, everyone tells them that it does not have the same version

**Comment by Gondram** [comment]
Having the same issue here. Chromebook running v1.4.4.5 gets the same "not using the same version" error message. Server screenshot showing the attempt attached. 
![Splat](https://user-images.githubusercontent.com/8175014/201546055-7fe5a11b-1546-43f4-8775-9229ff83bfb8.JPG)

**Comment by KUKARAF** [comment]
Same here trying to connect from android version 1.4.4.5 build 977 from playstore.

**Comment by soldsito** [comment]
yes, android players with version 1.4.4.5 build 977 can not enter :c

**Comment by SirMonkeyBoy** [comment]
If you download the update it should be fixed in the latest version

**Comment by KUKARAF** [comment]
Confirmed! Works now. Thank you! Not sure if that was the same issue for @GokuModoSupreme but it potentially looks like this issue can be closed then.
