### ISSUE TITLE
Tileliquid bug

### ISSUE THREAD

**Issue by moisterrific** [Moneylover3246/Crossplay#5]
There's a desync issue that happens for mobile clients when water and lava mix into each other to create obsidian.

It appears normal for PC clients, but for mobile clients the water "freeze" above the lava and no obsidian is created. And obviously the mobile player falls thru the liquid bc they don't "receive" the obsidian tile update.

**Comment by Moneylover3246** [comment]
Fixed in the 1.4.2.1 patch
