### ISSUE TITLE
Outdated crossplay

### ISSUE THREAD

**Issue by TheOpOne1** [Moneylover3246/Crossplay#68]
Crossplay only goes up until v1.4.4.9 and the people I'm trying to play with are using v1.4.4.9.2.

**Comment by SirMonkeyBoy** [comment]
Hi can you see if this fixes the issue https://github.com/SirMonkeyBoy/Crossplay/releases/tag/v1.4.4.9.2_for_mobile I don't know if it will as I didn't get the same issue when I used the last version but it might

**Comment by TheOpOne1** [comment]
Hello,

Thank you for trying to resolve my issue, but I'm currently away from my
computer and I should be able to get back to you by Monday.

**Comment by Herobxxm** [comment]
Hello? I guess.

My mobile version of Terraria(v.1.4.4.9.2 build 1015) can not connect to the local server ( Connection timeout ). My Steam version(v.1.4.4.9) sure can join the server. Any Ideas?


> Hi can you see if this fixes the issue https://github.com/SirMonkeyBoy/Crossplay/releases/tag/v1.4.4.9.2_for_mobile I don't know if it will as I didn't get the same issue when I used the last version but it might

**Comment by SirMonkeyBoy** [comment]
I would recommend looking for an error in the ip or a port forwarding error if that applies.

**Comment by TheOpOne1** [comment]
Ok, I'll check it out.

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by Moneylover3246** [comment]
Yeah, you need to make sure you're port forwarding properly. Try finding resources on how to do so using your internet provider

As for a plugin update, 1.4.4.9.2 is a minor update which did not affect the multiplayer protocol, so this version of the plugin will still work without issues

**Comment by Herobxxm** [comment]
The devices are on the same network(wifi), so i don't think it is about port forwarding.

note: I can use pc version to connect mobile's without additional step, but the mobile can not connect to the pc.

**Comment by Moneylover3246** [comment]
Being on the same network still requires you to port forward through your internet provider. 

I'd recommend doing research on that or using a hosting service that handles everything instead
