### ISSUE TITLE
Blocks are not dropping.

### ISSUE THREAD

**Issue by Satobi46** [Moneylover3246/Crossplay#69]
when I chop down trees it does not drop anything and same with the blocks when I try to mine them.
I use pc Crossplay. I'm using this version of Crossplay plugin my TShock and Terraria is latest update.
![105600_20230702174650_1](https://github.com/Moneylover3246/Crossplay/assets/83565801/e7ff1c34-5f5e-4a4e-bb5e-35cbc18b06f4)
![105600_20230702174644_1](https://github.com/Moneylover3246/Crossplay/assets/83565801/81e362f0-55da-49e9-84af-223cf75afeb3)

**Comment by Moneylover3246** [comment]
Could you provide the exact version of crossplay you see during the launch screen? Also try removing the plugin to see if anything changes in regard to item drops

**Comment by Satobi46** [comment]
I use "Crossplay v2.2 for Terraria 1.4.4.9" and the latest "TShock 5.2 for Terraria 1.4.4.9".

![Screenshot 20asdasdasdasdasdasd23-07-03 104822](https://github.com/Moneylover3246/Crossplay/assets/83565801/0cd954d2-d528-4903-aa33-2ef9ddc73f5b)

**Comment by Satobi46** [comment]
I removed the plugin and everything works fine like chopping down trees or mining drops blocks.

**Comment by Satobi46** [comment]
bruhhh, This is closed this plugin is fine, I freshly installed tshock with only ur plugin using and it seems it's one of the plugin I Installed that makes the blocks no to drop

**Comment by Satobi46** [comment]
I think chat relay was conflicting the mod that's why maybe drops are not dropping.

**Comment by Satobi46** [comment]
Actually, none of the new plugins listed on the TShock Github causes the error, it seems like the real actual cult was some random plugin I installed 2 years ago which hasn't been updated for a while. Which means I just caused a random stupid disturbance here. 💀💀💀
