### ISSUE TITLE
v1.4.4.9.5

### ISSUE THREAD

**Issue by JaydenTJD** [Moneylover3246/Crossplay#74]
My friend has mobile version 1.4.4.9.5 and I play on steam v1.4.4.9. I notice that there isn't support for this mobile version. Does it just work or is there a way to add versions? If neither of those options are correct, how do I play with my friend?
![image](https://github.com/user-attachments/assets/c6a53807-1bd5-4f1e-be18-b316f06a61ac)

**Comment by SirMonkeyBoy** [comment]
1.4.4.9.5 is support in the current versions just get them to join they should be able to

**Comment by JaydenTJD** [comment]
@SirMonkeyBoy do i have to add them to the whitelist first?

**Comment by SirMonkeyBoy** [comment]
No they should be able to just join

**Comment by JaydenTJD** [comment]
ok

**Comment by JaydenTJD** [comment]
@SirMonkeyBoy I tried but it didnt work

**Comment by SirMonkeyBoy** [comment]
is their anything in the logs you can send and is it port forwarded if needed

**Comment by JaydenTJD** [comment]
@SirMonkeyBoy it is port forwarded and where do i find a log

**Comment by SirMonkeyBoy** [comment]
where you got this https://private-user-images.githubusercontent.com/187148790/382512691-c6a53807-1bd5-4f1e-be18-b316f06a61ac.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA2NzEwNjYsIm5iZiI6MTczMDY3MDc2NiwicGF0aCI6Ii8xODcxNDg3OTAvMzgyNTEyNjkxLWM2YTUzODA3LTFiZDUtNGYxZS1iZTE4LWIzMTZmMDZhNjFhYy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEwM1QyMTUyNDZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02ZjliYmFjZjFkYjhjYTQyYzdlZjYwOTYwZjllYWQ3YWM0MTNhOWY2ZDkwMjFlNDJmYzk5M2E1NjZmYzFiNDBhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.3loHKnKUFxQd7ArhOFAvA-m_kjCW9E_dwnVs9oJhkj0 when they try join see if any error show up in the console

**Comment by JaydenTJD** [comment]
It just doesnt do anything and on their end it says connection timed out

**Comment by SirMonkeyBoy** [comment]
can you send the logs just copy from the console and paste it into a message

**Comment by JaydenTJD** [comment]
it doesnt let me highlight it so i cant copy or paste

**Comment by SirMonkeyBoy** [comment]
you should be able to you will need to right click on the highlighted text and click the copy button their as consoles doesn't let you use CTRL+C

**Comment by JaydenTJD** [comment]
it doesnt let me highlight

**Comment by JaydenTJD** [comment]
![image](https://github.com/user-attachments/assets/0c8b3f74-644e-4771-8d17-0bcdb1374349)

**Comment by SirMonkeyBoy** [comment]
did they try and join

**Comment by JaydenTJD** [comment]
yes but nothing happened

**Comment by SirMonkeyBoy** [comment]
because if they did and it didn't show up their if it's your end with port forwarding or they have the wrong ip

**Comment by JaydenTJD** [comment]
its the correct ip because earlier i joined with the ip i gave

**Comment by SirMonkeyBoy** [comment]
where you on the same network as the server

**Comment by JaydenTJD** [comment]
yes

**Comment by SirMonkeyBoy** [comment]
you might want to try use your mobile data on your phone if you have any because if your on the same network it doesn't port forward

**Comment by JaydenTJD** [comment]
1. im not on my phone im on my pc
2. i dont have data

**Comment by SirMonkeyBoy** [comment]
well it looks like a error somewhere else then the server so i can't help you as i only now how to port forward on my own router

**Comment by JaydenTJD** [comment]
@SirMonkeyBoy is there anyone who can help me?

**Comment by SirMonkeyBoy** [comment]
youtube how to do it for your router

**Comment by JaydenTJD** [comment]
how to do what exactly

**Comment by SirMonkeyBoy** [comment]
search your router if you don't know what it is you will need to go find it can change just like put it into google or something i can't help you anymore then that

**Comment by JaydenTJD** [comment]
Sorry I forgot to close this
